### ISSUE TITLE
[Bug]: Crashes upon startup- log below

### ISSUE THREAD

**Issue by StaticTelly** [Zepalesque/Aether-Redux-Issue-Tracker#141]
### Minecraft Version

1.19.4

### Mod Version

1.0.1

### Forge/Neoforge Version

45.3.0

### What happened?

Crashes upon startup. Don't know if Dimensional Doors is causing it or not. Have used both 1.0.1 and 1.0 versions of Aether Redux and nothing works. Minecraft also loads just fine with only the Aether installed, and _not_ Redux as well. 

### What was the expected result?

Minecrafts loads as normal. 

### Steps to Reproduce

I believe just have Dimensional Doors and Aether Redux installed. 

### Log Output (if applicable)

https://mclo.gs/96J6C2e

### Is this a compatibility issue with another mod?

Dimensioanl Doors (potentially) 

### Make sure to confirm these as well before submitting the report:

- [X] The issue persists on the latest version of the mod.
- [X] All version numbers are properly recorded, no instances of ‘latest’
- [X] All details are reported clearly and concisely
- [X] This issue is not a duplicate of another issue
- [X] If the issue is a modpack-related issue, it only occurs *with* Redux installed, and not without
- [X] If the issue is a modpack-related issue, it has been reported to the modpack devs as well

**Comment by Zepalesque** [comment]
ah
i’ve been wondering if this’d ever come up

i stopped updating the 1.19.4 version quite a while ago, so it’s not up-to-date
if you use an older aether version (probably an older forge version too) you might be able to get it to work, but it’d be better to use a different mc version (1.19.2/1.20.1) since there have been a multitude of large improvements to this mod since v1.0.1 (for context — the latest version on the other mc versions is v2.0.17)

**Comment by StaticTelly** [comment]
tysm, imma be swapping to 1.19.2!
