### ISSUE TITLE
Feature Request: just could you update to the newest version of aeroblender us modpack devs prob get bothered when aeroblender needs to update but the newest one does not work with the mod

### ISSUE THREAD

**Issue by Thunderrock424242** [Zepalesque/Aether-Redux-Issue-Tracker#15]
**Please describe your request**
ex: There should be a snowy biome in the mod (MORE DETAIL THAN THIS PLEASE)

**Why do you think it should be added?**
ex: Because it would add a nice wintery vibe to some areas in the Aether (MORE DETAIL THAN THIS PLEASE)

**Do you have any specific ways of implementation in mind? (OPTIONAL)**
ex: The biome should have [biome feature #1] and [biome feature #2]

**Comment by Zepalesque** [comment]
okay so first of all, which aeroblender version are you using, and what error did you get?
also, what redux and minecraft version as well
Since the it *should* be working with the latest version

also, next time I’d suggest filling out the issue template - since just using the template without changing anything makes it harder to know the issue (I’d also say thia *probably* counts as a bug, but it’s fine)

**Comment by Thunderrock424242** [comment]
Nvm it works now

**Comment by Zepalesque** [comment]
ah 😂 well that’s good, glad it works lol
