### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by paulgb434** [Zepalesque/Aether-Redux-Issue-Tracker#36]
Hi! I just wanted to say thank u for mod, i was also wondering if there is a way to turn off berry trees from spawning in the aether ?I can't find anything in the config And if there isn't would there b a way to do it thru data packs ? Thanks!

**Comment by Zepalesque** [comment]
hmm, not sure which trees you mean by berry trees
could you give a screenshot?

**Comment by Zepalesque** [comment]
oh wait do you mean the chromatic bushes? If so, yeah you could likely remove them with a datapack

**Comment by Zepalesque** [comment]
if you mean something else though, it is still possible datapacks may be able to disable whatever it is, assuming that it’s a worldgen feature.
you coukd probably make a datapack that overrides the biome with a copy of itself with the feature removed from the biome

I’ll close this since hopefully that should answer your question, if not tou can reopen it

**Comment by paulgb434** [comment]
Hi! Thanks for responding, how can I go about removing the generation of those chromatic bushes with a datapack? I am completely at a loss here... I know how to use a datapack but I'm not sure on where to start to see how to do something like this

Tysm
