### ISSUE TITLE
Bug [1.19.2]: Crash when creating a superflat world

### ISSUE THREAD

**Issue by ZilverLazarus** [Zepalesque/Aether-Redux-Issue-Tracker#38]
**What version of the mod, Forge/Neoforge and Minecraft are you using?**
Forge 43.3.2

**Describe the bug**
The game freezes and generates a crash report when creating a superflat world.

**To Reproduce**
1. Launch game
2. Go to world creation menu
3. Create superflat world
4. Game freezes

**Expected behavior**
Of course, expected behavior is to load into the superflat world without issue.

**Screenshots**

**Crash report (if necessary and/or applicable)**
ex: [upload file here]

**Log file (should be titled latest.log, if applicable)**
ex: 
[crash-2023-11-28_01.53.53-server.txt](https://github.com/Zepalesque/Aether-Redux-Issue-Tracker/files/13484676/crash-2023-11-28_01.53.53-server.txt)

**Additional context**
This seems to be a conflict with another mod. Not sure which one though.

**Comment by Zepalesque** [comment]
Looking at your crash log, it appears you’re using an older version, v1.2.
This bug was actully already reported in issue #22 and then fixed in v1.3, so I’d recommend updating to the latest version of the mod (currently v1.3.3 as of writing this comment).

If updating doesn’t fix it then you can reopen the issue, but since I’m about 99% sure that’s the problem, I’ll close the issue for now.
